### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by caf-jamesl**
Changed the readme, take a look?

### CODE REVIEW

**Comment by caf-jamesl** [comment]
That is a really good change... Nice one!

**Comment by caf-jamesl** [comment]
Do it!

**Comment by doowruc** [comment]
I object whole-heartedly to this pointless rubbish change

**Comment by doowruc** [comment]
Also, the self-congratulatory, own-trumpet-blowing comment was totally unnecessary

**Pull request merged**
